# Header
menu:
  Home: /
  # Delete this row if you don't want categories in your header nav bar
  Categories: 
  About: /about/index.html

# Content
fancybox: true

# Thumbnail
thumbnail: true

# Sidebar
social_links:
  twitter: 
  facebook: 
  google_plus: 
  weibo: 
  rss: 
widgets:
- recent_posts
- category
- archive
- tag
- tagcloud
- links

# Links
links:
  Hexo: http://hexo.io

# Miscellaneous
google_analytics:
favicon: /favicon.png
fb_admins:
fb_app_id: